# ================================================================
# XGBoost Baseline – Fault-Detection (Binary Classification)
# ================================================================
model:
  - model_name: XGB_test_v1            
    description: >
      Baseline reproduced from Table 5 of
      “Combining Residual and LSTM Recurrent Networks for
      Transportation-Mode Detection …”.
      All XGBoost hyper-parameters are defined below.

    # -------- data set --------
    window_size: 300
    overlap: 0.3          
    num_elements: 20      
    num_class: 8

    # -------- training process placeholders (compatibility) --------
    batch_size: 4096
    epochs: 1
    criterion: null
    optimizer: null
    lr: 0.0

    # -------- XGBoost params --------
    xgb_params:
      n_estimators:     400
      learning_rate:    0.1
      max_depth:        10
      min_child_weight: 1
      subsample:        0.8
      colsample_bytree: 0.8
      gamma:            0.0
      reg_lambda:       1.0
      objective:        "multi:softmax"
      num_class:      8
      tree_method:      "hist"   
      random_state:     42
      n_jobs:           -1

    # -------- dicts --------
    log_dir:  "localExperiments/logs"
    ckpt_dir: "localExperiments/model_result/XGBoost_result"
