# ============================================================
# AdaBoost Baseline – 二分类故障检测
# ============================================================
model:
  - model_name: ADB_test_v1
    description: >
      依据论文 Table 5，baseline test for AdaBoost。


    window_size: 300
    overlap: 0.3
    num_elements: 8
    num_classes: 2


    batch_size: 4096  
    epochs: 1
    criterion: null
    optimizer: null
    lr: 0.0


    adaboost_params:
      n_estimators: 400        
      learning_rate: 0.1
      algorithm: "SAMME"    
      random_state: 42
      


    log_dir:  "localExperiments/logs"
    ckpt_dir: "localExperiments/model_result/adaboost"
