# ================================================================
#  LSTM-MLP Baseline – 8-Class Transportation Mode Detection
#  Table 5:  LSTM(128) – MLP(128-256-512-1024-8) – SoftMax
# ================================================================
model:
  - model_name: LSTM_MLP_test_v1

    window_size: 300         
    overlap:      0.3
    num_elements: 20          
    num_classes:  8

    batch_size:  1024
    epochs:      100
    lr:          1.0e-3
    dropout:     0.2           
    criterion:   CrossEntropyLoss
    optimizer:   Adam

    log_dir:  "localExperiments/logs"
    ckpt_dir: "localExperiments/model_result/lstm_mlp/checkpoints"
